#!/bin/bash
# Frontend configuration script

rs_path="$(pwd)/src/app/services/register.service.ts" # register.service.ts
ps_path="$(pwd)/src/app/services/places.service.ts" # places.service.ts

if [ $# -eq 0 ]; then # Check arguments existence
    echo "No arguments supplied"; exit 1
elif [ $1 = "-l" ]; then # Run on localhost
  echo "Localhost option selected"; sleep 0.3
  sed -i -e 's/192.168.99.101:3000/localhost:3000/g' $rs_path
  sed -i -e 's/192.168.99.101:3000/localhost:3000/g' $ps_path
  ng s
elif [ $1 = "-d" ]; then # Run on docker
  echo "Docker option selected"; sleep 0.3
  sed -i -e 's/localhost:3000/192.168.99.101:3000/g' $rs_path
  sed -i -e 's/localhost:3000/192.168.99.101:3000/g' $ps_path
  eval $(docker-machine env rancher-node1) # Select node1 and load blackend
  docker-compose build
  docker-compose up
else # Check different argument
  echo "Argument not allowed"; exit 1
fi
