#!/bin/bash
# Frontend configuration script

rs_path="$(pwd)/src/app/services/register.service.ts" # register.service.ts
ps_path="$(pwd)/src/app/services/places.service.ts"   # places.service.ts
if [ $# -eq 0 ]; then # Check options existence
  echo "No arguments supplied"
elif [ $# -gt 1 ]; then # Check options number
  echo "The number of option is greater than 1"
elif [ $1 = "-l" ]; then # Run on localhost
  echo "Localhost option selected"
  sed -i -e 's/192.168.99.101:3000/localhost:3000/g' $rs_path
  sed -i -e 's/192.168.99.101:3000/localhost:3000/g' $ps_path
  ng s --host 168.176.25.25 --port 4200 #interoperability
  ng s # localhost
elif [ $1 = "-d" ]; then # Run on docker
  echo "Docker option selected"
  sed -i -e 's/localhost:3000/192.168.99.101:3000/g' $rs_path
  sed -i -e 's/localhost:3000/192.168.99.101:3000/g' $ps_path
  eval $(docker-machine env rancher-node1)
  docker-compose build
  docker-compose up
else # Error message
  echo "ERROR: this option is not allowed"
fi
